# Generated by Django 5.0.6 on 2024-11-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('acronym', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('flavor_id', models.AutoField(primary_key=True, serialize=False)),
                ('flavor_name', models.CharField(max_length=255)),
                ('flavor_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverage.country')),
            ],
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('beverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('beverage_name', models.CharField(max_length=255)),
                ('beverage_description', models.TextField()),
                ('beverage_image', models.ImageField(upload_to='beverage_images/')),
                ('beverage_stock', models.IntegerField()),
                ('milliliters', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverage.company')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverage.flavor')),
            ],
        ),
    ]
