# Generated by Django 5.0.6 on 2024-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0002_alter_company_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='beverage_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
