# Generated by Django 5.0.6 on 2024-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverage', '0003_beverage_beverage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='beverage_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
